/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones = 'America/Sao_Paulo';

export interface Config {
  auth: {
    'portal-editors': PortalEditorAuthOperations;
  };
  blocks: {};
  collections: {
    'portal-editors': PortalEditor;
    'news-articles': NewsArticle;
    'news-media': NewsMedia;
    'news-schedules': NewsSchedule;
    'news-audit': NewsAudit;
    'legacy-news-revisions': LegacyNewsRevision;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'portal-editors': PortalEditorsSelect<false> | PortalEditorsSelect<true>;
    'news-articles': NewsArticlesSelect<false> | NewsArticlesSelect<true>;
    'news-media': NewsMediaSelect<false> | NewsMediaSelect<true>;
    'news-schedules': NewsSchedulesSelect<false> | NewsSchedulesSelect<true>;
    'news-audit': NewsAuditSelect<false> | NewsAuditSelect<true>;
    'legacy-news-revisions': LegacyNewsRevisionsSelect<false> | LegacyNewsRevisionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'news-home': NewsHome;
  };
  globalsSelect: {
    'news-home': NewsHomeSelect<false> | NewsHomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: PortalEditor;
  jobs: {
    tasks: {
      'publish-news-snapshot': TaskPublishNewsSnapshot;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface PortalEditorAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-editors".
 */
export interface PortalEditor {
  id: string;
  portalUid: string;
  email: string;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  collection: 'portal-editors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles".
 */
export interface NewsArticle {
  id: string;
  title?: string | null;
  category?: string | null;
  editorial?: {
    version: 1;
    kind: 'article' | 'edition';
    summary: string;
    author: string;
    source_label: string;
    source_date: string | null;
  } | null;
  body?:
    | (
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            text?: string | null;
            level?: number | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            text?: string | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraph';
          }
        | {
            items?:
              | {
                  text?: string | null;
                  id?: string | null;
                }[]
              | null;
            ordered?: boolean | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'list';
          }
        | {
            media?: (string | null) | NewsMedia;
            alt?: string | null;
            caption?: string | null;
            credit?: string | null;
            usage?: ('cover' | 'body') | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            tone?: ('info' | 'warning' | 'success') | null;
            title?: string | null;
            text?: string | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callout';
          }
        | {
            text?: string | null;
            attribution?: string | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
        | {
            name?: string | null;
            role?: string | null;
            text?: string | null;
            media?: (string | null) | NewsMedia;
            alt?: string | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            typography?: ('serif' | 'sans') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'profile';
          }
        | {
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'divider';
          }
        | {
            label?: string | null;
            url?: string | null;
            newTab?: boolean | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'link';
          }
        | {
            media?: (string | null) | NewsMedia;
            title?: string | null;
            usage?: ('edition' | 'attachment') | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pdf';
          }
        | {
            media?: (string | null) | NewsMedia;
            url?: string | null;
            title?: string | null;
            layout?: ('content' | 'wide' | 'full' | 'left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
      )[]
    | null;
  publishedAt?: string | null;
  publicationGeneration?: number | null;
  legacyDocumentId?: string | null;
  legacySourceId?: string | null;
  legacyRevisionId?: string | null;
  importedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Immutable assets. To replace or crop, upload a new asset and change the article reference.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-media".
 */
export interface NewsMedia {
  id: string;
  sha256: string;
  legacyAssetId?: string | null;
  importedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-schedules".
 */
export interface NewsSchedule {
  id: string;
  target: 'news-articles' | 'news-home';
  documentId: string;
  action: 'publish' | 'unpublish';
  versionId: string;
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  snapshotHash: string;
  scheduledAt: string;
  actorUid: string;
  generation: number;
  state: 'pending' | 'published' | 'unpublished' | 'cancelled' | 'rejected';
  jobId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-audit".
 */
export interface NewsAudit {
  id: string;
  action: 'draft_saved' | 'published' | 'unpublished' | 'scheduled' | 'schedule_cancelled' | 'schedule_rejected';
  documentId: string;
  versionId?: string | null;
  actorUid: string;
  requestedByUid: string;
  details:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-news-revisions".
 */
export interface LegacyNewsRevision {
  id: string;
  legacyDocumentId: string;
  legacyRevisionId: string;
  originalVersion: number;
  originalCreatedAt: string;
  originalActorUid?: string | null;
  originalStatus: 'draft' | 'published' | 'scheduled' | 'archived';
  originalTitle: string;
  originalCategory?: string | null;
  originalPublishedAt?: string | null;
  originalBody:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  originalEditorial?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentHash: string;
  provenanceHash: string;
  mediaReferences?: (string | NewsMedia)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'publish-news-snapshot';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'publish-news-snapshot') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'portal-editors';
        value: string | PortalEditor;
      } | null)
    | ({
        relationTo: 'news-articles';
        value: string | NewsArticle;
      } | null)
    | ({
        relationTo: 'news-media';
        value: string | NewsMedia;
      } | null)
    | ({
        relationTo: 'news-schedules';
        value: string | NewsSchedule;
      } | null)
    | ({
        relationTo: 'news-audit';
        value: string | NewsAudit;
      } | null)
    | ({
        relationTo: 'legacy-news-revisions';
        value: string | LegacyNewsRevision;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'portal-editors';
    value: string | PortalEditor;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'portal-editors';
    value: string | PortalEditor;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-editors_select".
 */
export interface PortalEditorsSelect<T extends boolean = true> {
  portalUid?: T;
  email?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-articles_select".
 */
export interface NewsArticlesSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  editorial?: T;
  body?:
    | T
    | {
        richText?:
          | T
          | {
              content?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              level?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        paragraph?:
          | T
          | {
              text?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        list?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              ordered?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              alt?: T;
              caption?: T;
              credit?: T;
              usage?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        callout?:
          | T
          | {
              tone?: T;
              title?: T;
              text?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              text?: T;
              attribution?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        profile?:
          | T
          | {
              name?: T;
              role?: T;
              text?: T;
              media?: T;
              alt?: T;
              layout?: T;
              typography?: T;
              id?: T;
              blockName?: T;
            };
        divider?:
          | T
          | {
              layout?: T;
              id?: T;
              blockName?: T;
            };
        link?:
          | T
          | {
              label?: T;
              url?: T;
              newTab?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        pdf?:
          | T
          | {
              media?: T;
              title?: T;
              usage?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              media?: T;
              url?: T;
              title?: T;
              layout?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  publicationGeneration?: T;
  legacyDocumentId?: T;
  legacySourceId?: T;
  legacyRevisionId?: T;
  importedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-media_select".
 */
export interface NewsMediaSelect<T extends boolean = true> {
  sha256?: T;
  legacyAssetId?: T;
  importedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-schedules_select".
 */
export interface NewsSchedulesSelect<T extends boolean = true> {
  target?: T;
  documentId?: T;
  action?: T;
  versionId?: T;
  snapshot?: T;
  snapshotHash?: T;
  scheduledAt?: T;
  actorUid?: T;
  generation?: T;
  state?: T;
  jobId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-audit_select".
 */
export interface NewsAuditSelect<T extends boolean = true> {
  action?: T;
  documentId?: T;
  versionId?: T;
  actorUid?: T;
  requestedByUid?: T;
  details?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legacy-news-revisions_select".
 */
export interface LegacyNewsRevisionsSelect<T extends boolean = true> {
  legacyDocumentId?: T;
  legacyRevisionId?: T;
  originalVersion?: T;
  originalCreatedAt?: T;
  originalActorUid?: T;
  originalStatus?: T;
  originalTitle?: T;
  originalCategory?: T;
  originalPublishedAt?: T;
  originalBody?: T;
  originalEditorial?: T;
  contentHash?: T;
  provenanceHash?: T;
  mediaReferences?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-home".
 */
export interface NewsHome {
  id: string;
  eyebrow?: string | null;
  headline?: string | null;
  summary?: string | null;
  publishedAt?: string | null;
  publicationGeneration?: number | null;
  legacyDocumentId?: string | null;
  legacySourceId?: string | null;
  legacyRevisionId?: string | null;
  importedAt?: string | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-home_select".
 */
export interface NewsHomeSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  summary?: T;
  publishedAt?: T;
  publicationGeneration?: T;
  legacyDocumentId?: T;
  legacySourceId?: T;
  legacyRevisionId?: T;
  importedAt?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPublish-news-snapshot".
 */
export interface TaskPublishNewsSnapshot {
  input: {
    scheduleId: string;
  };
  output: {
    state: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}